### ISSUE TITLE
ApplicationConfig.js: this.sharedSubscription is always falsy in getClientId()

### ISSUE THREAD

**Issue by jsuntiok** [ibm-watson-iot/iot-nodejs#142]
We are looking for this.options.mqtt.sharedSubscription in constructor and we set that to false if it's not set.
No this.sharedSubscription is set.

**Comment by JonahIBM** [comment]
Hey - I'll look into this for you. 

There are the 2 primary ways to set your sharedSubscription to true by either using the environment variables
`export WIOTP_OPTIONS_MQTT_SHAREDSUBSCRIPTION = true`

   or by including a .yaml file, eg:
 ```
   identity:
      appId: myApp
    auth:
      key: myKey
      token: myToken
    options:
      domain: internetofthings.ibmcloud.com
      mqtt:
        sharedSubscrption: true
        port: 8883
        transport: tcp
        cleanStart: false
```
Either way by default it will always be set to false if no value is provided. https://github.com/ibm-watson-iot/iot-nodejs/blob/dfd5ced69f40ee4ce0438f9166d0f4e938c8a99c/src/application/ApplicationConfig.js#L101

Just so I can better understand where this issue lies, which of the 2 methods above did you use to set your sharedSubscription setting?
